import { describe, it, expect } from 'vite-plus/test';
import { readFileSync, readdirSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Fence for issues #560 and #569.
 *
 * cdk-local pins `docker --platform` to each Lambda's declared
 * `Architectures` (the template value is read at
 * `src/local/lambda-resolver.ts` and mapped by `architectureToPlatform`).
 * A function that declares no `architecture` defaults to `x86_64`, so on
 * an arm64 host its container runs `linux/amd64` under CPU emulation --
 * where the Go RIE inside the `public.ecr.aws/lambda/*` base images
 * faults intermittently (`fatal error: fault`, `select on synctest
 * channel from outside bubble`, `sync: inconsistent mutex state`),
 * failing a DIFFERENT assertion on every run.
 *
 * Converted fixtures therefore declare the HOST's architecture, which is
 * native on an Apple Silicon dev host and on an x86_64 CI runner alike.
 * This file exists because the failure mode is silent and
 * environment-dependent: a new handler added without `architecture` would
 * pass on CI (amd64, where the default IS the host arch) and reintroduce
 * a flaky arm64-only failure that costs another diagnosis cycle. The
 * fixtures' own `verify.sh` scripts send stderr to `/dev/null`, so even
 * cdk-local's "running under emulation" warning is invisible during a
 * normal run -- this file is the only thing standing between a new
 * handler and a silent regression.
 *
 * ## Every fixture source file is in exactly one bucket
 *
 * The suites below are generated by iterating the bucket arrays, so on
 * their own they would be blind to a DELETION: drop a path from
 * `HOST_ARCHITECTURE_STACKS` and its tests simply stop being generated,
 * and the run stays green having checked nothing. That is the
 * table-driven-off-the-set-under-test trap.
 *
 * `discovers every fixture that constructs a *Function(` closes it from
 * the other side. It walks `tests/integration/<fixture>/{lib,bin}` for
 * real (non-comment) `*Function(` constructor calls and asserts the
 * discovered set EQUALS the union of the four buckets. A deletion, an
 * addition, a renamed file, and a SECOND stack file inside an
 * already-listed fixture (`local-start-api-all-stacks/lib/stack-a.ts`
 * and `stack-b.ts` are exactly that shape) all become loud.
 *
 * ## Caveat the converted fixtures point at
 *
 * `process.arch` is the architecture of the Node process running the CDK
 * app, NOT the Docker daemon's. A Rosetta-emulated Node, or a
 * `DOCKER_HOST` / `docker context` aimed at a foreign-arch daemon, can
 * still declare the non-native arch. Neither is the ordinary local case,
 * and cdk-local's own emulation warning still fires when it happens.
 *
 * ## `NOT_YET_CONVERTED` empty is the completion signal for #569
 *
 * Each batch of #569 moves paths out of `NOT_YET_CONVERTED` and into
 * `HOST_ARCHITECTURE_STACKS`. When that array is empty, every fixture
 * Lambda in the repo declares the host architecture -- provably, rather
 * than by assertion. Do not add a path there to silence a failure: a
 * file in that bucket is asserted NOT to define `HOST_ARCHITECTURE`, so
 * parking a converted fixture in it fails immediately.
 */

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const INTEG_ROOT = path.join(REPO_ROOT, 'tests', 'integration');

/**
 * The exact declaration every converted fixture must carry.
 *
 * Compared against the source with whitespace collapsed, so reformatting
 * is fine but the SEMANTICS are pinned: hardcoding either architecture
 * would merely move the emulation to the other host (`ARM_64` makes an
 * amd64 CI runner emulate; `X86_64` is the default that caused #560 on
 * arm64). Only the host-derived form is native on both.
 */
const HOST_ARCH_DECL =
  "const HOST_ARCHITECTURE = process.arch === 'arm64' ? lambda.Architecture.ARM_64 : lambda.Architecture.X86_64;";

/**
 * Lambda constructor spellings this fence understands, mapped to the
 * architecture property each one requires.
 *
 * The L1 `CfnFunction` takes a `string[]` of architecture NAMES rather
 * than the L2 `Architecture` object, which is why it needs its own entry.
 */
const LAMBDA_CTORS = new Map<string, string>([
  ['new lambda.Function(', 'architecture: HOST_ARCHITECTURE'],
  ['new lambda.CfnFunction(', 'architectures: [HOST_ARCHITECTURE.name]'],
  ['new lambda.DockerImageFunction(', 'architecture: HOST_ARCHITECTURE'],
]);

/**
 * `*Function(` constructors that are NOT Lambdas and have no
 * `architecture` at all.
 *
 * A CloudFront Function is a different service entirely; it runs on
 * CloudFront's edge, not in a container, so there is nothing to pin.
 *
 * This set is an escape hatch, and the failure message for an
 * unrecognized spelling points contributors straight at it -- so it is
 * pinned to a literal below (`the non-Lambda allowlist is exactly the
 * reviewed set`). Adding `lambda.DockerImageFunction` here, for
 * instance, would silence the fence for every container Lambda in the
 * repo; that edit now fails and has to be argued for in review.
 */
const NON_LAMBDA_CTORS = new Set<string>(['new cloudfront.Function(']);

/** Fixture sources required to run their Lambdas at the host architecture. */
const HOST_ARCHITECTURE_STACKS = [
  'tests/integration/local-start-api/lib/local-start-api-stack.ts',
  'tests/integration/local-start-api-websocket/lib/stack.ts',
  'tests/integration/local-invoke/lib/local-invoke-stack.ts',
  'tests/integration/local-invoke-assume-role/lib/local-invoke-assume-role-stack.ts',
  'tests/integration/local-invoke-layers/lib/local-invoke-layers-stack.ts',
  'tests/integration/local-invoke-python/lib/local-invoke-python-stack.ts',
  'tests/integration/local-invoke-ruby/lib/local-invoke-ruby-stack.ts',
  'tests/integration/local-invoke-java/lib/local-invoke-java-stack.ts',
  'tests/integration/local-invoke-dotnet/lib/local-invoke-dotnet-stack.ts',
];

/**
 * Fixture sources whose architecture is pinned to a PREBUILT ARTIFACT and
 * must NOT be converted to the host architecture.
 */
const PINNED_STACKS = [
  {
    relPath: 'tests/integration/local-invoke-provided/lib/local-invoke-provided-stack.ts',
    pin: 'architecture: lambda.Architecture.X86_64',
    why:
      'its verify.sh cross-compiles the bootstrap with GOARCH=amd64, so the declared ' +
      'architecture must match the BINARY, not the host; converting it to ' +
      'HOST_ARCHITECTURE would hand an arm64 base image an amd64 executable and RIE ' +
      'would fail with `exec format error`',
  },
];

/**
 * The #569 BACKLOG: fixture sources that do not yet declare the host
 * architecture. Empty means #569 is complete.
 *
 * "Does not declare the host architecture" covers two shapes, not one.
 * Most of these simply omit `architecture` and so default to `x86_64`.
 * `local-studio` is the other shape -- it hardcodes
 * `lambda.Architecture.ARM_64`, which is native on an Apple Silicon dev
 * host but makes an amd64 CI runner emulate instead, so it is wrong in
 * the mirror-image way and still needs converting.
 *
 * This is a backlog, NOT the home for a NEW fixture. Anything created
 * from `/create-integ` declares the host architecture from the start and
 * belongs in `HOST_ARCHITECTURE_STACKS`; adding a new fixture here would
 * defer the completion signal above forever.
 *
 * Listed rather than globbed so that converting one is a visible move
 * between two literal arrays, and so a fixture cannot join this bucket
 * silently.
 */
const NOT_YET_CONVERTED = [
  'tests/integration/local-invoke-buildkit/lib/local-invoke-buildkit-stack.ts',
  'tests/integration/local-invoke-container/lib/local-invoke-container-stack.ts',
  'tests/integration/local-invoke-from-cfn-stack/lib/local-invoke-from-cfn-stack-stack.ts',
  'tests/integration/local-invoke-from-cfn-stack-large-stack/lib/local-invoke-from-cfn-stack-large-stack-stack.ts',
  'tests/integration/local-invoke-from-cfn-stack-multi-stack/lib/consumer-stack.ts',
  'tests/integration/local-list/lib/local-list-stack.ts',
  'tests/integration/local-start-alb-lambda/lib/local-start-alb-lambda-stack.ts',
  'tests/integration/local-start-alb-websocket/lib/local-start-alb-websocket-stack.ts',
  'tests/integration/local-start-api-all-stacks/lib/stack-a.ts',
  'tests/integration/local-start-api-all-stacks/lib/stack-b.ts',
  'tests/integration/local-start-api-cognito-jwt/lib/local-start-api-cognito-jwt-stack.ts',
  'tests/integration/local-start-api-container/lib/local-start-api-container-stack.ts',
  'tests/integration/local-start-api-from-cfn-stack/lib/local-start-api-from-cfn-stack-stack.ts',
  'tests/integration/local-start-api-rest-v1-non-proxy/lib/local-start-api-rest-v1-non-proxy-stack.ts',
  'tests/integration/local-start-api-watch/lib/watch-stack.ts',
  'tests/integration/local-start-cloudfront-edge/lib/local-start-cloudfront-edge-stack.ts',
  'tests/integration/local-start-cloudfront-lambda-url/lib/local-start-cloudfront-lambda-url-stack.ts',
  'tests/integration/local-start-cloudfront-lambda-url-from-cfn-stack/lib/local-start-cloudfront-lambda-url-from-cfn-stack-stack.ts',
  'tests/integration/local-studio/lib/local-studio-stack.ts',
];

/**
 * Fixture sources that match `*Function(` but construct NO Lambda at all
 * -- CloudFront Functions only. They have nothing to declare, and they
 * are listed so the discovery check can account for them without the
 * fence pretending they are unconverted Lambdas (which would mean
 * `NOT_YET_CONVERTED` could never reach empty).
 */
const NON_LAMBDA_ONLY = [
  'tests/integration/local-start-cloudfront/lib/local-start-cloudfront-stack.ts',
  'tests/integration/local-start-cloudfront-kvs-from-cfn-stack/lib/local-start-cloudfront-kvs-from-cfn-stack-stack.ts',
];

/**
 * Every `new <ns...>.<Name>Function(` constructor call, in any spelling.
 *
 * The namespace part is `(?:...)*` rather than `(?:...)?` on purpose:
 * with a single optional segment, the standard submodule form
 * `new cdk.aws_lambda.Function(` does not match at all, so a handler
 * written that way would be a SILENT PASS -- exactly the case this fence
 * exists to catch. Matching the broad shape and then requiring every hit
 * to be a recognized spelling turns an unknown constructor into a loud
 * failure instead.
 */
const ANY_FUNCTION_CTOR = /new\s+(?:[A-Za-z_$][\w$]*\s*\.\s*)*[\w$]*Function\s*\(/g;

/**
 * Known blind spots, recorded rather than chased: a renamed import
 * (`import { Function as Fn }` -> `new Fn(`), an aliased binding
 * (`const F = lambda.Function`), a parenthesized callee
 * (`new (lambda.Function)(`), and generics. All require going out of the
 * way, none appears in this repo, and closing them means parsing rather
 * than matching. The discovery assertion still accounts for the FILE, so
 * the damage is bounded to a construct inside an already-listed fixture.
 */

/**
 * Remove comments so neither the discovery scan nor the per-call property
 * check can be satisfied by inert text.
 *
 * Without this, `// architecture: HOST_ARCHITECTURE` inside a constructor
 * call satisfies the "declares the architecture" assertion while the
 * synthesized template carries no `Architectures` key at all, and a
 * `new lambda.Function(` written in a JSDoc block pulls an unrelated file
 * into the discovery set. Quote state is tracked so a `//` inside a
 * string literal (a URL, say) is not mistaken for a comment.
 */
function stripComments(source: string): string {
  let out = '';
  let i = 0;
  let quote: string | null = null;
  while (i < source.length) {
    const ch = source[i];
    const next = source[i + 1];
    if (quote) {
      if (ch === '\\') {
        out += ch + (next ?? '');
        i += 2;
        continue;
      }
      if (ch === quote) quote = null;
      out += ch;
      i++;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === '`') {
      quote = ch;
      out += ch;
      i++;
      continue;
    }
    if (ch === '/' && next === '/') {
      while (i < source.length && source[i] !== '\n') i++;
      continue;
    }
    if (ch === '/' && next === '*') {
      i += 2;
      while (i < source.length && !(source[i] === '*' && source[i + 1] === '/')) i++;
      i += 2;
      continue;
    }
    out += ch;
    i++;
  }
  return out;
}

/** Collapse internal whitespace so `new  lambda . Function (` compares equal. */
function normalizeCtor(spelling: string): string {
  return spelling.replace(/\s+/g, '').replace('new', 'new ');
}

/**
 * Return the source text of every `needle` call in `source`, delimited by
 * paren matching rather than a line regex so both the single-line and the
 * wrapped `new lambda.Function(\n  this,\n  'Id',\n  {...}\n)` spellings
 * are covered.
 */
function constructorCalls(source: string, needle: string): string[] {
  const calls: string[] = [];
  let from = 0;
  for (;;) {
    const start = source.indexOf(needle, from);
    if (start === -1) break;
    let depth = 0;
    let end = start + needle.length - 1;
    for (let i = start + needle.length - 1; i < source.length; i++) {
      const ch = source[i];
      if (ch === '(') depth++;
      else if (ch === ')') {
        depth--;
        if (depth === 0) {
          end = i;
          break;
        }
      }
    }
    calls.push(source.slice(start, end + 1));
    from = end + 1;
  }
  return calls;
}

/** Name a call by its construct id, so a failure points at the function to fix. */
function constructId(call: string): string {
  return /new\s+[\w$.]*\(\s*this,\s*'([^']+)'/.exec(call)?.[1] ?? call.slice(0, 80).trim();
}

const read = (relPath: string): string =>
  stripComments(readFileSync(path.join(REPO_ROOT, relPath), 'utf8'));

/** Walk `tests/integration/<fixture>/{lib,bin}` for fixture source files. */
function discoverFixtureSources(): string[] {
  const found: string[] = [];
  for (const fixture of readdirSync(INTEG_ROOT, { withFileTypes: true })) {
    if (!fixture.isDirectory()) continue;
    for (const sub of ['lib', 'bin']) {
      const dir = path.join(INTEG_ROOT, fixture.name, sub);
      let entries: string[];
      try {
        entries = readdirSync(dir, { recursive: true }) as string[];
      } catch {
        continue; // fixture has no lib/ or bin/
      }
      for (const entry of entries) {
        if (!entry.endsWith('.ts')) continue;
        const abs = path.join(dir, entry);
        const rel = path.relative(REPO_ROOT, abs);
        if (rel.includes('node_modules') || rel.includes('cdk.out')) continue;
        const source = stripComments(readFileSync(abs, 'utf8'));
        if (new RegExp(ANY_FUNCTION_CTOR.source).test(source)) found.push(rel);
      }
    }
  }
  return found.sort();
}

describe('integ fixture Lambdas run at the host architecture (issues #560, #569)', () => {
  describe('bucket bookkeeping', () => {
    it('discovers every fixture that constructs a *Function( and accounts for it in exactly one bucket', () => {
      const discovered = discoverFixtureSources();
      const accounted = [
        ...HOST_ARCHITECTURE_STACKS,
        ...PINNED_STACKS.map((p) => p.relPath),
        ...NOT_YET_CONVERTED,
        ...NON_LAMBDA_ONLY,
      ].sort();

      // Equality, not a subset check, in BOTH directions at once:
      //  - a path discovered but unaccounted = a new (or renamed, or
      //    second-in-a-fixture) source nobody has classified;
      //  - a path accounted but not discovered = a stale entry for a file
      //    that was deleted or renamed, whose generated tests would
      //    otherwise vanish silently.
      expect(
        discovered,
        'fixture sources constructing a *Function( must be listed in exactly one of ' +
          'HOST_ARCHITECTURE_STACKS / PINNED_STACKS / NOT_YET_CONVERTED / NON_LAMBDA_ONLY. ' +
          'A NEW fixture declares the host architecture from the start (see ' +
          '.claude/skills/create-integ/SKILL.md) and goes in HOST_ARCHITECTURE_STACKS -- ' +
          'NOT_YET_CONVERTED is the #569 backlog, not a landing spot for new work. ' +
          'A path here that no longer exists should be deleted from its bucket'
      ).toEqual(accounted);
    });

    it('puts each path in only one bucket', () => {
      const all = [
        ...HOST_ARCHITECTURE_STACKS,
        ...PINNED_STACKS.map((p) => p.relPath),
        ...NOT_YET_CONVERTED,
        ...NON_LAMBDA_ONLY,
      ];
      const dupes = all.filter((p, i) => all.indexOf(p) !== i);
      expect(dupes, 'these paths appear in more than one bucket').toEqual([]);
    });

    it('recognizes every constructor spelling in EVERY fixture, not just the converted ones', () => {
      // The per-fixture spelling check below runs only inside the
      // converted loop, so an unrecognized spelling anywhere else was a
      // silent pass -- and those files are precisely the ones the
      // remaining #569 batches are about to convert. Checking the whole
      // discovered set means a spelling this fence cannot read is caught
      // when it is WRITTEN rather than when its fixture is converted.
      const offenders: string[] = [];
      for (const relPath of discoverFixtureSources()) {
        for (const m of read(relPath).matchAll(ANY_FUNCTION_CTOR)) {
          const spelling = normalizeCtor(m[0]);
          if (!LAMBDA_CTORS.has(spelling) && !NON_LAMBDA_CTORS.has(spelling)) {
            offenders.push(`${relPath}: ${spelling}`);
          }
        }
      }
      expect(
        offenders,
        'constructor spelling(s) this fence does not understand. Write the call as one of ' +
          `[${[...LAMBDA_CTORS.keys()].join(', ')}], or add it to NON_LAMBDA_CTORS if the ` +
          'construct genuinely is not a Lambda. Left unlisted, the architecture check ' +
          'would silently skip it once this fixture is converted'
      ).toEqual([]);
    });

    it('keeps the pinned list exactly the reviewed set', () => {
      // The hardcode failure tells contributors to "move it to
      // PINNED_STACKS instead", which makes this array an escape hatch
      // from every per-construct assertion: a regressed fixture moved
      // here passes with any `pin` and any `why`. NON_LAMBDA_CTORS got a
      // change-detector for exactly this reason; this array needs the
      // same one, or the advice in that message is a way out.
      expect(
        PINNED_STACKS.map((p) => p.relPath),
        'PINNED_STACKS exempts a fixture from declaring the host architecture. Adding one ' +
          'is a claim that its handler is a PREBUILT binary compiled for a specific ' +
          'architecture -- update this assertion in the same commit so it is reviewed'
      ).toEqual([
        'tests/integration/local-invoke-provided/lib/local-invoke-provided-stack.ts',
      ]);
    });

    it('keeps the non-Lambda allowlist exactly the reviewed set', () => {
      // A change-detector on purpose. The "spelling this fence does not
      // understand" failure names NON_LAMBDA_CTORS as a way out, so
      // without this an unrecognized Lambda constructor can be silenced
      // by one line rather than fixed.
      expect(
        [...NON_LAMBDA_CTORS],
        'NON_LAMBDA_CTORS silences the architecture check for a constructor entirely. ' +
          'Adding one is a deliberate claim that the construct is not a Lambda and has ' +
          'no architecture -- update this assertion in the same commit so it is reviewed'
      ).toEqual(['new cloudfront.Function(']);

      const lambdaish = [...NON_LAMBDA_CTORS].filter((c) => c.includes('lambda.'));
      expect(
        lambdaish,
        'these entries name the lambda namespace, so they are Lambdas and DO take an architecture'
      ).toEqual([]);
    });
  });

  // The helpers above are otherwise exercised only by the happy path of
  // real fixture files, which all pass. These feed synthetic sources through
  // them so the DISCRIMINATING behaviour is pinned before 19 more fixtures
  // come to depend on it.
  describe('the fence helpers themselves', () => {
    const wrap = (body: string) => `class S { constructor() {${body}} }`;

    it('does not let a commented-out property satisfy the architecture check', () => {
      const src = stripComments(
        wrap(`new lambda.Function(this, 'A', {
          runtime: R,
          // architecture: HOST_ARCHITECTURE,
        });`)
      );
      const [call] = constructorCalls(src, 'new lambda.Function(');
      expect(call.includes('architecture: HOST_ARCHITECTURE')).toBe(false);
    });

    it('keeps a `//` inside a string literal', () => {
      expect(stripComments(`const u = 'https://example.com/x';`)).toContain('https://example.com/x');
    });

    it('detects a spaced constructor spelling through the count cross-check', () => {
      const src = wrap(`new lambda . Function (this, 'A', {});`);
      const hits = [...src.matchAll(ANY_FUNCTION_CTOR)];
      expect(hits).toHaveLength(1);
      // Recognized once normalized, but the literal-keyed matcher cannot
      // delimit it -- which is exactly what the count check reports.
      expect(normalizeCtor(hits[0][0])).toBe('new lambda.Function(');
      expect(constructorCalls(src, 'new lambda.Function(')).toHaveLength(0);
    });

    it('matches a deeper namespace than one segment', () => {
      const hits = [...wrap(`new cdk.aws_lambda.Function(this, 'A', {});`).matchAll(ANY_FUNCTION_CTOR)];
      expect(hits).toHaveLength(1);
      expect(LAMBDA_CTORS.has(normalizeCtor(hits[0][0]))).toBe(false);
    });

    it('delimits two sibling calls separately rather than swallowing the second', () => {
      const src = wrap(`new lambda.Function(this, 'A', { code: f(g(1)) });
        new lambda.Function(this, 'B', {});`);
      const calls = constructorCalls(src, 'new lambda.Function(');
      expect(calls).toHaveLength(2);
      expect(calls.map(constructId)).toEqual(['A', 'B']);
    });

    it('names a wrapped call by its construct id', () => {
      const src = wrap(`new lambda.Function(
        this,
        'Wrapped',
        { runtime: R }
      );`);
      expect(constructorCalls(src, 'new lambda.Function(').map(constructId)).toEqual(['Wrapped']);
    });

    it('treats the CloudFront Function spelling as a non-Lambda', () => {
      const hits = [...wrap(`new cloudfront.Function(this, 'F', {});`).matchAll(ANY_FUNCTION_CTOR)];
      const spelling = normalizeCtor(hits[0][0]);
      expect(LAMBDA_CTORS.has(spelling)).toBe(false);
      expect(NON_LAMBDA_CTORS.has(spelling)).toBe(true);
    });
  });

  describe('converted fixtures', () => {
    for (const relPath of HOST_ARCHITECTURE_STACKS) {
      describe(relPath, () => {
        it('derives HOST_ARCHITECTURE from process.arch, mapping arm64 -> ARM_64 and everything else -> X86_64', () => {
          const normalized = read(relPath).replace(/\s+/g, ' ');
          expect(
            normalized,
            `${relPath} must contain exactly this declaration (whitespace-insensitive):\n\n` +
              `    ${HOST_ARCH_DECL}\n\n` +
              'Hardcoding either architecture only moves the emulation to the other host.'
          ).toContain(HOST_ARCH_DECL);
        });

        it('defines its Lambdas only via constructor spellings this fence understands', () => {
          // Guards the assumption the next test depends on. Without this, a
          // handler added as `NodejsFunction` / `new Function(` / a deeper
          // namespace path would not be found at all, and "every construct
          // declares the architecture" would be vacuously true of it.
          const source = read(relPath);
          const found = [...source.matchAll(ANY_FUNCTION_CTOR)].map((m) => normalizeCtor(m[0]));
          const unknown = found.filter(
            (spelling) => !LAMBDA_CTORS.has(spelling) && !NON_LAMBDA_CTORS.has(spelling)
          );

          expect(
            unknown,
            `${relPath}: constructor spelling(s) this fence does not understand. Write the ` +
              `call as one of [${[...LAMBDA_CTORS.keys()].join(', ')}]. Only add to ` +
              `NON_LAMBDA_CTORS if the construct genuinely is not a Lambda`
          ).toEqual([]);
          expect(found.length, `${relPath} should declare at least one Lambda`).toBeGreaterThan(0);
        });

        it('declares the host architecture on every Lambda construct', () => {
          const source = read(relPath);
          const seen: string[] = [];
          const missing: string[] = [];

          for (const [ctor, requiredProp] of LAMBDA_CTORS) {
            for (const call of constructorCalls(source, ctor)) {
              seen.push(call);
              // `source` is comment-stripped, so a commented-out
              // `// architecture: HOST_ARCHITECTURE` cannot satisfy this.
              if (!call.includes(requiredProp)) {
                missing.push(`${constructId(call)} (needs \`${requiredProp}\`)`);
              }
            }
          }

          const regexHits = [...source.matchAll(ANY_FUNCTION_CTOR)].filter((m) =>
            LAMBDA_CTORS.has(normalizeCtor(m[0]))
          ).length;
          expect(
            seen.length,
            `${relPath}: this fence found ${regexHits} Lambda constructor(s) but could only ` +
              `delimit ${seen.length} of them, so some went unchecked. This normally means a ` +
              'call is written with spaces inside the constructor name -- write it as ' +
              '`new lambda.Function(` (no spaces before the paren)'
          ).toBe(regexHits);
          expect(seen.length, `${relPath} should declare at least one Lambda`).toBeGreaterThan(0);

          expect(
            missing,
            `${relPath}: these Lambda constructs are missing their architecture ` +
              `declaration, which reintroduces issue #560 (amd64 emulation on arm64 ` +
              `hosts) for them`
          ).toEqual([]);
        });

        it('never hardcodes an architecture, which would only move the emulation to the other host', () => {
          // Delete the one sanctioned mention -- the declaration itself --
          // and nothing may remain. Done on whitespace-collapsed text so
          // the check does not depend on the formatter keeping the ternary
          // on one line (a `printWidth` change would otherwise red this
          // suite with advice to use PINNED_STACKS, which is wrong advice).
          const normalized = read(relPath).replace(/\s+/g, ' ');
          const withoutDecl = normalized.replace(HOST_ARCH_DECL, '');
          // Optional namespace: a named import (`import { Architecture }`) spells it
          // `Architecture.ARM_64`, with no `lambda.` prefix to key on.
          const offenders =
            withoutDecl.match(/(?:[\w$]+\.)?Architecture\.(?:ARM_64|X86_64)/g) ?? [];

          expect(
            offenders,
            `${relPath}: hardcoded architecture(s) found outside the HOST_ARCHITECTURE ` +
              `declaration. Hardcoding ARM_64 makes an amd64 CI runner emulate; hardcoding ` +
              `X86_64 is the default that caused #560 on arm64 hosts. If this fixture ` +
              `genuinely must pin an architecture to match a prebuilt binary, move it to ` +
              `PINNED_STACKS instead`
          ).toEqual([]);
        });

        it('does not set Architectures through an escape hatch the fence cannot read', () => {
          // `addPropertyOverride('Architectures', ...)` after construction
          // would override the declared value while leaving the
          // constructor call looking correct -- green fence, emulated
          // container.
          const source = read(relPath);
          const overrides = source
            .split('\n')
            .filter((line) => /add(?:Property)?Override\s*\(/.test(line))
            .filter((line) => /architectures?/i.test(line));
          expect(
            overrides,
            `${relPath}: an Architectures override bypasses the declared architecture. ` +
              'Set it on the constructor instead'
          ).toEqual([]);
        });
      });
    }
  });

  describe('fixtures pinned to a prebuilt binary', () => {
    // If PINNED_STACKS were emptied, this describe would generate no tests
    // at all -- but the discovery assertion above would fail first, because
    // the pinned file would no longer be accounted for in any bucket. That
    // is the intended backstop: it does not depend on Vitest's "No test
    // found in suite" behaviour, which stops applying the moment a second
    // pinned fixture exists.
    for (const { relPath, pin, why } of PINNED_STACKS) {
      describe(relPath, () => {
        it('pins the architecture on EVERY L2 Lambda construct, not just one', () => {
          // `expect(source).toContain(pin)` would be satisfied by a single
          // surviving pin. This fixture has two L2 functions, so deleting
          // one pin would leave the other and keep such a check green while
          // an amd64 binary is handed to an arm64 base image.
          const source = read(relPath);
          const calls = constructorCalls(source, 'new lambda.Function(');
          expect(
            calls.length,
            `${relPath} should declare at least one lambda.Function`
          ).toBeGreaterThan(0);

          const unpinned = calls
            .filter((call) => !call.includes(pin))
            .map((call) => constructId(call));
          expect(unpinned, `${relPath}: these constructs lost \`${pin}\`: ${why}`).toEqual([]);
        });

        it('is not converted to HOST_ARCHITECTURE', () => {
          expect(
            read(relPath).includes('HOST_ARCHITECTURE'),
            `${relPath} must NOT be converted: ${why}`
          ).toBe(false);
        });
      });
    }
  });

  describe('fixtures not yet converted (#569 is complete when this list is empty)', () => {
    for (const relPath of NOT_YET_CONVERTED) {
      it(`${relPath} is genuinely unconverted, so it is parked here honestly`, () => {
        // Stops the bucket being used as a dumping ground: a fixture that
        // HAS been converted cannot be parked here to dodge the per-file
        // assertions above, and a converted fixture that regressed cannot
        // be "fixed" by moving its path down here.
        expect(
          read(relPath).includes('HOST_ARCHITECTURE'),
          `${relPath} defines HOST_ARCHITECTURE, so it belongs in HOST_ARCHITECTURE_STACKS ` +
            'where the per-construct assertions apply -- move it up rather than leaving it here'
        ).toBe(false);
      });
    }
  });

  describe('fixtures whose only *Function( constructs are not Lambdas', () => {
    for (const relPath of NON_LAMBDA_ONLY) {
      it(`${relPath} constructs no Lambda`, () => {
        const source = read(relPath);
        const lambdaHits = [...source.matchAll(ANY_FUNCTION_CTOR)]
          .map((m) => normalizeCtor(m[0]))
          .filter((spelling) => LAMBDA_CTORS.has(spelling));
        expect(
          lambdaHits,
          `${relPath} now constructs a Lambda, so it must move to NOT_YET_CONVERTED or ` +
            'HOST_ARCHITECTURE_STACKS'
        ).toEqual([]);
      });
    }
  });
});
